### PR TITLE
handle types that don't define `#respond_to?` despite `#method_missing`

### PR DESCRIPTION
**Pull request by aybabtme**
hello halp @nanzhong

### CODE REVIEW

**Comment by aybabtme** [comment]
@phillbaker yoyoyo

**Comment by bobbytables** [comment]
Ah... crafty. :+1:

**Comment by nanzhong** [comment]
This handles problem introduced by libraries like https://github.com/grpc/grpc, that don't correctly update `#respond_to?` when using `#method_missing`.

:+1:

**Comment by bobbytables** [comment]
Oddly enough we had a similar problem with grpc. So I'm glad to see this getting fixed.

**Pull request merged**
