### PR TITLE
Reduce the number of objects allocated by Kartograph when generating JSON objects.

### PR DESCRIPTION
**Pull request by vinibaggio**
Kartograph can be quite memory hungry depending on your JSON data. By
using stackprof, I was able to reduce roughly 30% less allocated memory.
This has significant performance impact since there will be a lot less
GC pauses. For instance, the integration test goes from 3.9s in my
machine down to 0.7s.

### CODE REVIEW

**Comment by mauricio** [comment]
CI doesn't seem happy?

**Comment by vinibaggio** [comment]
@mauricio yeah, 👀

**Comment by vinibaggio** [comment]
some stackprof samples:

before:
screen shot 2018-01-30 at 9 29 19 pm

after:
screen shot 2018-01-30 at 9 29 21 pm

Note that it is still highly recommended to use a different JSON renderer than ruby's default.

**Comment by mauricio** [comment]
LGTM when 💚

**Pull request merged**
